/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */
plugins {
    id("org.jetbrains.kotlin.jvm") version "2.2.21"
    id("io.ktor.plugin") version "3.3.3"
    kotlin("plugin.serialization") version "2.3.0"
    application
}

repositories {
    mavenCentral()
}

val ktor_version = "3.3.3"
dependencies {
    // Testing
    testImplementation(libs.junit.jupiter.engine)
    testImplementation("io.ktor:ktor-server-test-host:$ktor_version")
    testImplementation("org.jetbrains.kotlin:kotlin-test:2.2.21")
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.2")
    implementation("io.ktor:ktor-server-core-jvm:$ktor_version")
    implementation("io.ktor:ktor-server-netty:$ktor_version")
    implementation("io.ktor:ktor-server-config-yaml:$ktor_version")
    implementation("ch.qos.logback:logback-classic:1.4.11")

    // Ktor Client
    implementation("io.ktor:ktor-client-core:$ktor_version")
    implementation("io.ktor:ktor-client-cio:$ktor_version")    
    // Client Serialization
    implementation("io.ktor:ktor-client-content-negotiation:$ktor_version")
    // Server Serialization
    implementation("io.ktor:ktor-server-content-negotiation:$ktor_version")
    // JSON Serialization
    implementation("io.ktor:ktor-serialization-kotlinx-json:$ktor_version")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0")
    // Error Handling
    implementation("io.ktor:ktor-server-status-pages:$ktor_version")
    // CORS
    implementation("io.ktor:ktor-server-cors:$ktor_version")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "org.dopc.AppKt"
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}
